services:
  # Backend API
  backend:
    build:
      context: ./backend/BoardGamesTrackerApi
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-5001}:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      # host.docker.internal allows Docker container to connect to host machine's SQL Server
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=BoardGamesDb;User Id=dockeruser;Password=dockerdbboardgames1!;TrustServerCertificate=True;
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Ensures host.docker.internal works on Linux

  # Frontend Angular App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-4300}:80"
    environment:
      - API_URL=http://backend:5001