name: Test Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Install Playwright
      run: |
        cd PlaywrightTestsDotNet
        dotnet build
        pwsh bin/Debug/net8.0/playwright.ps1 install
    
    - name: Start Docker Services
      run: docker compose --profile e2e --profile acceptance up -d --build
    
    - name: Wait for services to be ready
      run: sleep 15
    
    - name: Run All Tests
      run: pwsh ./run-all-tests.ps1
      continue-on-error: true
    
    - name: Docker Compose Down
      if: always()
      run: docker compose down
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          PlaywrightTestsDotNet/TestResults/
          PlaywrightTestsDotNet/bin/Debug/net8.0/playwright-traces/
        retention-days: 7

  smoke-test-only:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Install Playwright
      run: |
        cd PlaywrightTestsDotNet
        dotnet build
        pwsh bin/Debug/net8.0/playwright.ps1 install
    
    - name: Start Docker Services
      run: docker compose --profile e2e up -d --build
    
    - name: Wait for services to be ready
      run: sleep 15
    
    - name: Run Smoke Tests
      run: pwsh ./run-smoke-tests.ps1
    
    - name: Docker Compose Down
      if: always()
      run: docker compose down